name: First workflow
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      -name:print greeting
       run:echo "Hello World"
      -name:print good
       run:echo "good bye"
       
      -
